<a href="https://colab.research.google.com/github/niranjan-1785/ml_lab/blob/main/Experiment_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [5]:
import urllib.request

# Download the wine quality red dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
filename = 'winequality-red.csv'

try:
    urllib.request.urlretrieve(url, filename)
    print("Dataset downloaded successfully!")
except Exception as e:
    print(f"Error downloading dataset: {e}")

Dataset downloaded successfully!

In [6]:
df = pd.read_csv("winequality-red.csv", sep=";")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [7]:
X = df.drop("quality", axis=1)
y = (df["quality"] >= 6).astype(int)
print("Dataset shape:", df.shape)
print("Class counts:")
print(y.value_counts().rename(index={0: 'Not Good', 1: 'Good'}))

Dataset shape: (1599, 12)
Class counts:
quality
Good        855
Not Good    744
Name: count, dtype: int64

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 1279
Testing samples: 320

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
architectures = [
    (10,),
    (20,),
    (20, 10),
    (50, 25)
]

results = []

for architecture in architectures:
    model = MLPClassifier(
        hidden_layer_sizes=architecture,
        activation="relu",
        solver="adam",
        max_iter=1000,
        random_state=42
    )
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    results.append({
        "Architecture": str(architecture),
        "Accuracy (%)": round(accuracy * 100, 2)
    })
    print("Architecture:", architecture, "Accuracy:", round(accuracy * 100, 2), "%")

Architecture: (10,) Accuracy: 75.62 %
Architecture: (20,) Accuracy: 77.5 %

/usr/local/lib/python3.13/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Architecture: (20, 10) Accuracy: 77.81 %
Architecture: (50, 25) Accuracy: 78.44 %

In [11]:
results_df = pd.DataFrame(results)
results_df.sort_values(by='Accuracy (%)', ascending=False).reset_index(drop=True)

  Architecture  Accuracy (%)
0     (50, 25)         78.44
1     (20, 10)         77.81
2        (20,)         77.50
3        (10,)         75.62